# Site settings

google_analytics: G-T42Y6EV0LX

#header_pages:
#  - index.md
#  - about.md

footer: 'Copyright (c) 2024 Ru Keïn'

style: dark #light # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag
