# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

footer: 'Copyright (c) 2020 Ru Keïn'

style: dark #light # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag
